USE ATENDIMENTO;

DELETE FROM CDFUNCIONARIO;
DELETE FROM CDCLIENTE;
DELETE FROM LCATENDIMENTO;
DELETE FROM CDESCOLA;
DELETE FROM cddependente;

INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (1, 'RENATO DE ALMEIDA JUNIOR', 'AV. 7 DE SETEMBRO', '658', '17458965', 'CENTRO', 'MARILIA', 'SP', '1979-05-25', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (2, 'CARLA GONÇALVEZ DIAS', 'AV. 8 DE DEZEMBRO', '857', '18745896', 'SERRARIA', 'BAURU', 'SP', '1985-05-01', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (3, 'ANTONIO APARECIDO DOS SANTOS', 'AV. RIO BRANCO', '748', '17485963', 'CENTRO', 'MARILIA', 'SP', '1986-06-01', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (4, 'FVW`!Jjn::p<e4 *\Shh4skB8V|51A', 'ALAMEDA AGOSTINHO DELLA', '831', '92846338', 'ESPIGAO D''OESTE', 'MASSAPE DO PIAUI', 'PR', '1984-04-21', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (5, 'ALEIXO MAX MAZZAQUATRO', 'R JOÃO ARANHA', '854', '78852677', 'COLORADO DO OESTE', 'JENIPAPO DE MINAS', 'ES', '1978-08-03', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (6, 'ADAIR JOSE MANUEL', 'R DR ADEMAR PEREIRA DE BARROS', '491', '37529796', 'CEREJEIRA', 'JENIPAPO DE MINAS', 'PA', '1975-04-01', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (7, 'ALESSANDRO MONTEIRO DE', 'R PROF JOAQUIM PEDROSO', '924', '26451376', 'AMAJARI', 'PORTO DE MOZ', 'RO', '1986-02-17', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (8, 'ADEMIR SCOBIN', 'R JOSE DAVINHA', '9314', '23991766', 'VALE DO ANARI', 'CAAPIRANGA', 'AP', '1979-03-22', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (9, 'CHIAPPINI', 'R 7 DE SETEMBRO', '633', '25276339', 'CEREJEIRA', 'UIRAPURU', 'MT', '1997-06-01', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (10, 'ADELCIO RODRIGUES DE AGUILAR', 'R GUADALAJARA', '898', '24598247', 'PACARAIMA', 'NOVO PROGRESSO', 'MG', '1967-07-16', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (11, 'CLAUDEMIR ALVES PEREIRA', 'R ANTONIO FERRAZO', '712', '39964821', 'ROLIM DE MOURA', 'NOVA PORTEIRINHA', 'RN', '1961-05-16', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (12, 'ELICIO BARBOSA FERREIRA', 'R ANTONIO FESSEL', '1389', '29997877', 'PRESIDENTE MEDICI', 'PORTEL', 'AP', '1983-10-27', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (13, 'ADEMIR ANTONIO', 'R ALBERTO STUCKI', '3589', '81687386', 'VALE DO ANARI', 'DAVINOPOLIS', 'PA', '1997-07-13', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (14, 'DILMAR JOSE', 'R ANDRE MADSEN', '2758', '56982468', 'OURO PRETO DO OESTE', 'BACABEIRA', 'AC', '1973-08-19', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (15, 'CLAUDEMIR LEMES BARBOSA', 'R VEREADOR HERMINIO CONTESINI', '1247', '18826529', 'CANTA', 'FLORESTA DO ARAGUAIA', 'PB', '1989-09-05', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (16, 'CLAUDEMIR LEMES BARBOSA', 'R JUVENAL L. DE CAMARGO', '368', '21756587', 'PRESIDENTE MEDICI', 'UNIAO DE MINAS', 'RS', '1993-04-11', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (17, 'AGUINALDO RIBEIRO', 'R ROVIGO', '1729', '14164987', 'PRESIDENTE MEDICI', 'CENTRO NOVO DO MARANHAO', 'SP', '1974-05-28', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (18, 'ELICIO BARBOSA FERREIRA', 'AV PROF CARVALHO PINTO', '476', '19511391', 'ROLIM DE MOURA', 'BOQUEIRAO DO PIAUI', 'PB', '1973-01-18', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (19, 'ELICIO BARBOSA FERREIRA', 'R DAVID LOPES DE CAMARGO', '3268', '47744415', 'VALE DO ANARI', 'FLORESTA DO ARAGUAIA', 'ES', '1993-04-27', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (20, 'ADSON DO NASCIMENTO BARBOSA', 'AV DAS MACIEIRAS', '5396', '41993193', 'ROLIM DE MOURA', 'TRAIRAO', 'DF', '1966-08-09', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (21, 'DIRCE APARECIDA CUNHA MACIEL', 'R RAUL SILVA', '6312', '17572551', 'VALE DO ANARI', 'IPIXUNA DO PARA', 'DF', '1976-01-18', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (22, 'CAMARGO', 'ALAMEDA AGOSTINHO DELLA', '184', '24674341', 'PACARAIMA', 'TRAIRAO', 'PR', '1986-01-04', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (23, 'ANDRE LUIZ DA SILVA', 'R CANARIO', '395', '55168413', 'CAROEBE', 'BACURI', 'SE', '1970-05-27', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (24, 'EDINIR CARLOS MINOURO CUBO', 'R JULIO DE TOLEDO', '1963', '78872396', 'ROLIM DE MOURA', 'TRAIRAO', 'PB', '1999-02-11', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (25, 'EDSON FRANCISCO DA FONSECA', 'R AMAZONAS', '751', '64681114', 'CANTA', 'UIRAPURU', 'RJ', '1971-09-23', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (26, 'ALESSANDRO MONTEIRO DE', 'R PROF JOAQUIM PEDROSO', '6833', '64427775', 'VALE DO ANARI', 'FLORESTA DO PIAUI', 'RS', '1967-09-13', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (27, 'ALEXANDRE DE ARAUJO AMORIM', 'R VEREADOR HERMINIO CONTESINI', '9213', '59551862', 'ESPIGAO D''OESTE', 'MARTINS SOARES', 'SP', '1998-07-11', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (28, 'ANTONIO JOAO DA SILVA', 'R PROF JOAQUIM PEDROSO', '8135', '59993723', 'CEREJEIRA', 'ARAGOMINAS', 'SP', '1969-09-08', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (29, 'CLAUDEMIR BATISTA', 'R 7 DE SETEMBRO', '6361', '65249693', 'ROLIM DE MOURA', 'LAGOA DA CONFUSAO', 'DF', '1989-12-18', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (30, 'ADMILSON NUNES DE RESENDE', 'R MICÃO', '934', '55461572', 'TEIXEIROPOLIS', 'PAULINO NEVES', 'GO', '1978-04-07', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (31, 'ALEIXO MAX MAZZAQUATRO', 'R ANCHIETA', '588', '73579629', 'PACARAIMA', 'URUCURITUBA', 'SP', '1977-07-29', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (32, 'ADMILSON NUNES DE RESENDE', 'R DR MOACIR DO AMARAL', '5618', '26127875', 'COSTA MARQUES', 'SANTA LUZIA DO PARA', 'GO', '1969-03-29', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (33, 'ELISEU BRANCO', 'R RAUL SILVA', '431', '17955853', 'COSTA MARQUES', 'UNIAO DE MINAS', 'MA', '1996-09-07', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (34, 'EDSON FRANCISCO DA FONSECA', 'R ROVIGO', '6911', '41724963', 'VALE DO ANARI', 'TRAIRAO', 'DF', '1998-07-10', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (35, 'EDSON FRANCISCO DA FONSECA', 'R EUGENIO BERTTI', '1662', '26768155', 'CAROEBE', 'SAO JOAO DA BALIZA', 'ES', '1991-09-29', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (36, 'EDILSON JOSÉ DA SILVA', 'R GUADALAJARA', '8318', '62847335', 'CEREJEIRA', 'LAGOA DA CONFUSAO', 'RN', '1969-06-19', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (37, 'CLAUDEMIR ALVES PEREIRA', 'R ANTONIO SOUZA PEREZ', '9244', '27482383', 'JARU', 'CAMPO AZUL', 'PA', '1978-01-01', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (38, 'ALLAN MAGIOLI', 'AV WALDEMAR GOMES MARINHO', '191', '64372587', 'VALE DO ANARI', 'PORTO DE MOZ', 'ES', '1976-09-12', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (39, 'ALEIXO MAX MAZZAQUATRO', 'R 7 DE ABRIL', '1917', '66341311', 'SAO FELIPE D''OESTE', 'CENTRO NOVO DO MARANHAO', 'TO', '1964-10-28', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (40, 'ADSON DO NASCIMENTO BARBOSA', 'R DR MOACIR DO AMARAL', '898', '64747223', 'OURO PRETO DO OESTE', 'SETUBINHA', 'PB', '1960-02-23', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (41, 'ABEL MARIA DE CAMARGO', 'R ALBERTO STUCKI', '6227', '66768466', 'PIMENTEIRAS DO OESTE', 'MINISTRO ANDREAZZA', 'AP', '1964-07-05', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (42, 'CICERO JOSE DA SILVA', 'R MICÃO', '4925', '85134698', 'VALE DO ANARI', 'TABAPORA', 'MG', '1972-12-25', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (43, 'BENY ALLAN ROLIM BARBOSA', 'R PAULO ROBERTO BORELLI', '9247', '24331188', 'SAO FELIPE D''OESTE', 'SAO LUIZ', 'AP', '1967-06-09', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (44, 'ADEMAR PORTO', 'AV DONATELO', '9717', '61688731', 'COSTA MARQUES', 'PROFESSOR JAMIL', 'RJ', '1986-08-10', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (45, 'ALEIXO MAX MAZZAQUATRO', 'R JOÃO ARANHA', '284', '79115248', 'PRESIDENTE MEDICI', 'JENIPAPO DE MINAS', 'ES', '1975-12-17', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (46, 'CARLOS ALEXANDRE DA SILVA', 'R ALVARENGA PEIXOTO', '4788', '25226128', 'SAO FELIPE D''OESTE', 'COTRIGUACU', 'AP', '1964-08-20', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (47, 'CHIAPPINI', 'R SEBASTIAO BUENO FERRAZ', '177', '15758677', 'CAROEBE', 'CACHOEIRA GRANDE', 'GO', '1969-06-26', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (48, 'DOUGLAS MARCELO VIEIRA', 'R SAO PAULO', '445', '37712422', 'PRESIDENTE MEDICI', 'PORTO DE MOZ', 'RN', '1990-10-05', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (49, 'ANDRE LUIZ DA SILVA', 'R JOAO PESSOA', '3913', '88158768', 'TEIXEIROPOLIS', 'URUCURITUBA', 'DF', '1998-02-15', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (50, 'ELSON SILVA', 'R ANTONIO CARLOS NOGUEIRA', '8589', '32939571', 'JARU', 'COXIXOLA', 'PA', '1980-12-07', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (51, 'EDSON FRANCISCO DA FONSECA', 'R FRANCISCO D. DE OLIVEIRA', '6275', '29151431', 'PIMENTEIRAS DO OESTE', 'CAMPO AZUL', 'TO', '1996-09-03', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (52, 'DANIELLE BITTENCOURT LIASCH', 'R JOAO XXIII', '697', '86244612', 'ROLIM DE MOURA', 'BOQUEIRAO DO PIAUI', 'TO', '1994-10-02', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (53, 'ALOIZIO LUZ DE ALMEIDA BARROS', 'AV PROF CARVALHO PINTO', '348', '97164668', 'VALE DO ANARI', 'SANTO ANTONIO DO ICA', 'ES', '1990-06-20', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (54, 'ALINE DE CASSIA KARWOWSKI', 'R FRANCISCO D. DE OLIVEIRA', '5782', '48426785', 'TEIXEIROPOLIS', 'COXIXOLA', 'ES', '1977-01-15', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (55, 'SEBASTIÃO', 'AV DONATELO', '8635', '86314542', 'VALE DO ANARI', 'SANTA LUZIA DO PARA', 'RR', '1976-05-24', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (56, 'ALLAN MAGIOLI', 'R RAUL SILVA', '1169', '22178267', 'PACARAIMA', 'JUVENILIA', 'AC', '1965-08-23', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (57, 'ALEIXO MAX MAZZAQUATRO', 'R VEREADOR HERMINIO CONTESINI', '6245', '31984158', 'TEIXEIROPOLIS', 'ALTO CAPARAO', 'AL', '1965-09-13', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (58, 'ADAIR JOSE MANUEL', 'R ALVARENGA PEIXOTO', '968', '73133617', 'OURO PRETO DO OESTE', 'CENTRAL DO MARANHAO', 'MA', '1972-08-28', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (59, 'ARIOVALDO JOSE PINTO', 'R 7 DE SETEMBRO', '856', '61839894', 'CAROEBE', 'BACABEIRA', 'PA', '1988-03-04', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (60, 'ABEL MARIA DE CAMARGO', 'AV DAS MACIEIRAS', '8128', '98168999', 'SAO FELIPE D''OESTE', 'ARACOIABA', 'BA', '1965-07-17', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (61, 'BENY ALLAN ROLIM BARBOSA', 'R ALADINO SELMI', '5445', '54986166', 'SAO FELIPE D''OESTE', 'MARTINS SOARES', 'MA', '1975-05-26', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (62, 'CLAUDEMIR BATISTA', 'R VALTER ZACARIAS', '123', '55851437', 'VALE DO ANARI', 'MONTE FORMOSO', 'SP', '1995-08-10', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (63, 'CARLOS ALEXANDRE DA SILVA', 'R FRANCISCO D. DE OLIVEIRA', '2565', '39729853', 'VALE DO ANARI', 'CAMPO AZUL', 'MT', '1989-04-26', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (64, 'ANTONIO FURMAN', 'R LAVEIRO GIUZIO', '4276', '41614366', 'CEREJEIRA', 'PORTEL', 'PB', '1983-07-14', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (65, 'ALINE DE CASSIA KARWOWSKI', 'R SEBASTIAO BUENO FERRAZ', '4125', '39983984', 'VALE DO ANARI', 'JAPONVAR', 'RS', '1991-04-26', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (66, 'BENY ALLAN ROLIM BARBOSA', 'R SAO BENEDITO', '9528', '51173577', 'PACARAIMA', 'MASSAPE DO PIAUI', 'DF', '1964-03-05', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (67, 'ANDREA APARECIDA DE LIMA', 'R DAVID LOPES DE CAMARGO', '138', '65535996', 'SAO FELIPE D''OESTE', 'FLORESTA DO PIAUI', 'PB', '1961-02-01', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (68, 'ANTONIO JOAO DA SILVA', 'R ANTONIO SOUZA PEREZ', '1297', '32886667', 'JARU', 'BOQUEIRAO DO PIAUI', 'PR', '1993-02-21', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (69, 'ELISEU BRANCO', 'R FRANCISCO ALVES SIQUEIRA', '8941', '85622758', 'OURO PRETO DO OESTE', 'SAO JOAO DO PACUI', 'RS', '1988-07-01', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (70, 'EDVALDO LUIS GOMES', 'R JULIO DE TOLEDO', '6642', '14995761', 'VALE DO ANARI', 'LIMOEIRO DO AJURU', 'ES', '1969-02-20', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (71, 'ADELCIO RODRIGUES DE AGUILAR', 'R ATALIBA DE CARVALHO', '2828', '13515475', 'ROLIM DE MOURA', 'MONTE FORMOSO', 'RN', '1990-01-20', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (72, 'ERNESTO GALAFASSI GHINI', 'R VALTER ZACARIAS', '722', '24485193', 'VALE DO ANARI', 'ARAGOMINAS', 'GO', '1987-02-10', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (73, 'APARECIDO LIMA', 'R VALTER ZACARIAS', '434', '12794248', 'JARU', 'CENTRAL DO MARANHAO', 'CE', '1986-08-16', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (74, 'ALESSANDRO MONTEIRO DE', 'R SAO BENEDITO', '1793', '43723897', 'PRESIDENTE MEDICI', 'SANTO AMARO DO MARANHAO', 'PA', '1961-05-05', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (75, 'CLAUDEMIR BATISTA', 'R JOSE ZACARIAS', '5363', '68496214', 'ROLIM DE MOURA', 'ALTO CAPARAO', 'RO', '1982-09-06', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (76, 'APARECIDO LIMA', 'SP 354', '3778', '29934981', 'TEIXEIROPOLIS', 'TRAIRAO', 'PI', '1996-01-20', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (77, 'ABEL MARIA DE CAMARGO', 'R SAO BENEDITO', '686', '57588681', 'PRESIDENTE MEDICI', 'RECURSOLANDIA', 'SP', '1993-09-26', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (78, 'CARLOS EDUARDO TEODORO DA', 'SP 354', '393', '22174931', 'COSTA MARQUES', 'SETUBINHA', 'PR', '1989-08-18', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (79, 'ELISEU BRANCO', 'R JOAO XXIII', '791', '69984194', 'OURO PRETO DO OESTE', 'JUTAI', 'GO', '1991-01-28', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (80, 'ALAN DIEGO NANINI', 'R JOSE BONIFACIO', '3187', '34346831', 'PRESIDENTE MEDICI', 'SANTO ANTONIO DO ICA', 'RO', '1972-10-23', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (81, 'CHARKES ALBERT FERNANDES', 'AV DONATELO', '318', '87763772', 'COSTA MARQUES', 'NOVO PROGRESSO', 'RO', '1972-07-16', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (82, 'ANTANIO LUIZ VIEIRA DO', 'R JOÃO ARANHA', '3463', '96274226', 'VALE DO ANARI', 'FLORESTA DO PIAUI', 'AP', '1984-01-15', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (83, 'EDVALDO LUIS GOMES', 'R LARANJEIRAS', '1515', '86365864', 'TEIXEIROPOLIS', 'SANTO AMARO DO MARANHAO', 'PB', '1981-03-07', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (84, 'ARIOVALDO JOSE PINTO', 'R MONTE CASTELO', '1918', '83998462', 'AMAJARI', 'URUCURITUBA', 'RN', '1964-05-16', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (85, 'ANTONIA ANGELICA FOGASA', 'R SAO PAULO', '664', '19126884', 'JARU', 'SAO LUIZ', 'MT', '1984-11-01', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (86, 'ALINE DE CASSIA KARWOWSKI', 'R ANTONIO FESSEL', '4616', '12173371', 'SAO FELIPE D''OESTE', 'TRAIRAO', 'GO', '1981-03-13', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (87, 'ANDREA APARECIDA DE LIMA', 'R MICÃO', '1997', '37974819', 'TEIXEIROPOLIS', 'IPIXUNA DO PARA', 'DF', '1987-02-15', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (88, 'CICERO JOSE DA SILVA', 'R DR MOACIR DO AMARAL', '927', '98859319', 'ROLIM DE MOURA', 'MINISTRO ANDREAZZA', 'DF', '1998-04-26', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (89, 'CLAUDEMIR ALVES PEREIRA', 'AV PROF CARVALHO PINTO', '1437', '43897595', 'JARU', 'RECURSOLANDIA', 'TO', '1964-02-11', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (90, 'ANDERSON ROBERTO DE OLIVEIRA', 'R RICARDO ZERBI NATI', '8153', '84625283', 'PACARAIMA', 'SAO LUIZ', 'RS', '1976-12-01', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (91, 'ANTONIO ALVES DE ALMEIDA FILHO', 'R RICARDO ZERBI NATI', '8295', '56386884', 'TEIXEIROPOLIS', 'FLORESTA DO PIAUI', 'PA', '1963-06-13', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (92, 'DILMAR JOSE', 'R PROF JOAQUIM PEDROSO', '612', '27618767', 'OURO PRETO DO OESTE', 'ARAGOMINAS', 'RJ', '1974-11-13', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (93, 'DANIELLE BITTENCOURT LIASCH', 'AV DOS TRABALHADORES', '798', '69841459', 'PACARAIMA', 'URUARA', 'GO', '1963-05-05', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (94, 'ADAIR JOSE MANUEL', 'R ANTONIO FERRAZO', '787', '72681722', 'CAROEBE', 'COTRIGUACU', 'PB', '1981-03-25', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (95, 'ADEMAR PORTO', 'R RICARDO ZERBI NATI', '379', '13477971', 'PACARAIMA', 'PROFESSOR JAMIL', 'PA', '1989-01-17', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (96, 'ALINE DE CASSIA KARWOWSKI', 'R 10 DE ABRIL', '734', '94178615', 'JARU', 'TRAIRAO', 'MA', '1986-12-02', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (97, 'ABEL MARIA DE CAMARGO', 'R ANTONIO PEREIRA DA CRUZ', '3279', '14851346', 'OURO PRETO DO OESTE', 'PARAUAPEBAS', 'MT', '1996-06-26', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (98, 'CHIAPPINI', 'AV PAULICEIA', '8477', '75666112', 'VALE DO ANARI', 'SANTA FE DO ARAGUAIA', 'RO', '1981-01-16', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (99, 'APARECIDA DE SOUZA LIMA', 'R 7 DE SETEMBRO', '577', '83556315', 'VALE DO ANARI', 'CENTRAL DO MARANHAO', 'PR', '1979-09-07', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (100, 'CARLOS EDUARDO TEODORO DA', 'R PAULO ROBERTO BORELLI', '694', '24129477', 'SAO FELIPE D''OESTE', 'MARTINS SOARES', 'CE', '1981-05-27', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (101, 'EDILSON JOSÉ DA SILVA', 'R CANARIO', '286', '76676518', 'CEREJEIRA', 'JUNCO DO MARANHAO', 'RR', '1984-12-27', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (102, 'ADEMIR ANTONIO', 'R JOSE DAVINHA', '458', '13698241', 'VALE DO ANARI', 'URUARA', 'AP', '1990-09-03', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (103, 'BENY ALLAN ROLIM BARBOSA', 'AV CENTENARIO DR PAULO DE', '191', '13158238', 'CEREJEIRA', 'MONTE FORMOSO', 'AC', '1961-07-04', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (104, 'ERIC EMILIO DE CAMPOS', 'AV DA SAUDADE', '261', '39582494', 'ROLIM DE MOURA', 'JUVENILIA', 'GO', '1980-09-09', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (105, 'EDVALDO LUIS GOMES', 'R JOSE DAVINHA', '446', '11713465', 'CALDAZINHA', 'MINISTRO ANDREAZZA', 'BA', '1972-08-24', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (106, 'GALLANI', 'R LUIZ STRAZZACAPA', '393', '26856792', 'SAO FELIPE D''OESTE', 'UIRAPURU', 'GO', '1998-02-06', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (107, 'EMERSON CASSIA DA SILVA', 'R 7 DE ABRIL', '1762', '33565436', 'PIMENTEIRAS DO OESTE', 'PORTEL', 'TO', '1989-04-19', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (108, 'OLIVEIRA', 'R DINO BANCHIERI', '642', '12881163', 'IRACEMA', 'BOQUEIRAO DO PIAUI', 'PB', '1960-09-15', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (109, 'ELISEU BRANCO', 'R JUVENAL L. DE CAMARGO', '477', '88168734', 'COLORADO DO OESTE', 'ALTO CAPARAO', 'SE', '1969-03-10', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (110, 'EDSON FRANCISCO DA FONSECA', 'R FRANCISCO D. DE OLIVEIRA', '4924', '57621241', 'OURO PRETO DO OESTE', 'DARCINOPOLIS', 'TO', '1970-08-07', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (111, 'CHIAPPINI', 'R PAULO ROBERTO BORELLI', '7813', '53358415', 'COSTA MARQUES', 'SETUBINHA', 'RS', '1977-11-17', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (112, 'CESAR DOS SANTOS DE AZEVEDO', 'R AMAZONAS', '2912', '35525877', 'CAROEBE', 'JENIPAPO DE MINAS', 'MT', '1969-10-31', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (113, 'DIRCE APARECIDA CUNHA MACIEL', 'R ANTONIO CARLOS NOGUEIRA', '7865', '85317244', 'TEIXEIROPOLIS', 'FLORESTA DO PIAUI', 'GO', '1974-10-12', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (114, 'ANDRE LUIZ DA SILVA', 'R JUVENAL L. DE CAMARGO', '6411', '37139581', 'JARU', 'FLORESTA DO PIAUI', 'PA', '1997-07-12', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (115, 'ADMILSON NUNES DE RESENDE', 'AV WALDEMAR GOMES MARINHO', '1247', '35466889', 'TEIXEIROPOLIS', 'SAO JOAO DA BALIZA', 'PB', '1978-04-26', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (116, 'DOUGLAS MARCELO VIEIRA', 'R 10 DE ABRIL', '437', '32193722', 'IRACEMA', 'SANTA FE DO ARAGUAIA', 'RO', '1985-07-25', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (117, 'ANDERSON OLIVEIRA DA SILVA', 'R JOÃO ARANHA', '447', '77387553', 'VALE DO ANARI', 'IPIXUNA DO PARA', 'PB', '1972-03-24', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (118, 'ALEXANDRE DE ARAUJO AMORIM', 'R VALTER ZACARIAS', '481', '35632475', 'VALE DO ANARI', 'BACURI', 'ES', '1993-08-04', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (119, 'ANDERSON OLIVEIRA DA SILVA', 'R EUGENIO BERTTI', '419', '82621142', 'PACARAIMA', 'LIMOEIRO DO AJURU', 'GO', '1974-08-28', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (120, 'CHARLES WEINGARTNER', 'R 7 DE SETEMBRO', '948', '51134694', 'TEIXEIROPOLIS', 'PORTEL', 'AP', '1970-06-15', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (121, 'ADEMIR SCOBIN', 'AV DA SAUDADE', '2254', '26879265', 'IRACEMA', 'URUARA', 'RO', '1972-05-26', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (122, 'DANIELLE BITTENCOURT LIASCH', 'R DINO BANCHIERI', '1232', '32925737', 'JARU', 'ARACOIABA', 'ES', '1980-05-30', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (123, 'EUCLIDES ANTONIO CASTELANI', 'R GUILHERME CONTESINE', '481', '81226622', 'ROLIM DE MOURA', 'DAVINOPOLIS', 'ES', '1968-12-25', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (124, 'ARI DE ALMEIDA', 'R LUIZ STRAZZACAPA', '487', '86951446', 'PACARAIMA', 'NOVA PORTEIRINHA', 'RO', '1968-05-02', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (125, 'ALOIZIO LUZ DE ALMEIDA BARROS', 'R LUIZ STRAZACAPA', '342', '93637711', 'PRESIDENTE MEDICI', 'CACHOEIRA GRANDE', 'AM', '1967-02-02', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (126, 'DIRCE APARECIDA CUNHA MACIEL', 'AV DA SAUDADE', '729', '81259558', 'CAROEBE', 'ARACOIABA', 'ES', '1987-07-30', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (127, 'ABEL MARIA DE CAMARGO', 'AV DOS TRABALHADORES', '5938', '49826186', 'OURO PRETO DO OESTE', 'IMBE DE MINAS', 'GO', '1973-04-13', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (128, 'ERNESTO GALAFASSI GHINI', 'R SEBASTIAO BUENO FERRAZ', '2946', '77428892', 'PIMENTEIRAS DO OESTE', 'CURRALINHO', 'RS', '1982-04-17', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (129, 'ELEI SANTANA', 'AV LUIS MILANO FILHO', '3274', '17217986', 'PACARAIMA', 'PAULINO NEVES', 'MA', '1987-12-28', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (130, 'CARLOS DE JESUS', 'R JOSE BONIFACIO', '1747', '75824687', 'CANTA', 'SEBASTIAO LEAL', 'AP', '1967-08-06', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (131, 'APARECIDA ELIZABETE RODRIGUES', 'R JOÃO ARANHA', '6534', '74288278', 'TEIXEIROPOLIS', 'SAO FRANCISCO DO PARA', 'PI', '1965-02-13', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (132, 'EUCLIDES ANTONIO CASTELANI', 'R ROVIGO', '3452', '29696639', 'IRACEMA', 'JUTAI', 'PI', '1982-11-30', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (133, 'CAMARGO', 'ALAMEDA AGOSTINHO DELLA', '461', '66226218', 'OURO PRETO DO OESTE', 'ALTO CAPARAO', 'TO', '1973-03-31', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (134, 'ANDERSON ROBERTO DE OLIVEIRA', 'R ALADINO SELMI', '4595', '38168485', 'TEIXEIROPOLIS', 'PORTEL', 'GO', '1986-02-23', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (135, 'ALEIXO MAX MAZZAQUATRO', 'R DAURI GOES DE MORAES', '9431', '33258638', 'JARU', 'CAMPO AZUL', 'SE', '1960-06-05', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (136, 'ARIOVALDO JOSE PINTO', 'R ALADINO SELMI', '9288', '66992513', 'PRESIDENTE MEDICI', 'JUTAI', 'RJ', '1962-10-20', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (137, 'ADEMIR SCOBIN', 'R JOSE EDUARDO', '4655', '31429496', 'COSTA MARQUES', 'BACURI', 'AC', '1988-01-22', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (138, 'ADEMIR ANTONIO', 'R ANTONIO CARLOS NOGUEIRA', '1689', '76661228', 'CAROEBE', 'NOVO PROGRESSO', 'AC', '1978-01-19', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (139, 'ADEMIR SCOBIN', 'R ROVIGO', '9653', '96663566', 'OURO PRETO DO OESTE', 'CENTRAL DO MARANHAO', 'PR', '1986-11-27', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (140, 'EDINIR CARLOS MINOURO CUBO', 'AV DAS MACIEIRAS', '1996', '35782916', 'TEIXEIROPOLIS', 'LIMOEIRO DO AJURU', 'PI', '1963-03-16', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (141, 'ALEIXO MAX MAZZAQUATRO', 'R JOSE ZACARIAS', '984', '14896464', 'SAO FELIPE D''OESTE', 'JOSENOPOLIS', 'BA', '1976-05-03', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (142, 'CHARLES WEINGARTNER', 'AV DAS MACIEIRAS', '7753', '94341523', 'COSTA MARQUES', 'MASSAPE DO PIAUI', 'SP', '1965-05-20', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (143, 'CICERO JOSE DA SILVA', 'R ANTONIO PEREIRA DA CRUZ', '7899', '97344424', 'VALE DO ANARI', 'DAVINOPOLIS', 'RO', '1975-05-27', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (144, 'AGUINALDO RIBEIRO', 'R SEBASTIAO BUENO FERRAZ', '617', '56751162', 'PACARAIMA', 'PORTEL', 'MT', '1993-10-17', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (145, 'APARECIDO LIMA', 'R ANTONIO FESSEL', '1237', '47314147', 'TEIXEIROPOLIS', 'ALVORADA D''OESTE', 'TO', '1982-05-05', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (146, 'ANGELO ANDRE BRUSTOLIN', 'AV LUIS MILANO FILHO', '4591', '59339721', 'ROLIM DE MOURA', 'MONTE FORMOSO', 'AL', '1982-02-27', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (147, 'ARIOVALDO JOSE PINTO', 'SP 354', '514', '59126172', 'VALE DO ANARI', 'FRANCISCOPOLIS', 'MT', '1968-07-17', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (148, 'ANTONIO JOAO DA SILVA', 'R TIRADENTES', '7565', '96225754', 'OURO PRETO DO OESTE', 'SAO RAIMUNDO DO DOCA BEZERRA', 'TO', '1976-03-21', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (149, 'SEBASTIÃO', 'R SAO PAULO', '6147', '93515312', 'VALE DO ANARI', 'CAMPO AZUL', 'PA', '1965-08-12', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (150, 'OLIVEIRA', 'AV WALDEMAR GOMES MARINHO', '5283', '34635635', 'VALE DO ANARI', 'LAGOA DA CONFUSAO', 'PR', '1986-07-25', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (151, 'AGUINALDO RIBEIRO', 'R ALVARENGA PEIXOTO', '635', '73794964', 'ROLIM DE MOURA', 'URUARA', 'ES', '1964-12-17', 'M');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (152, 'ELEI SANTANA', 'R ANDRE MADSEN', '9875', '56912818', 'ROLIM DE MOURA', 'CACHOEIRA GRANDE', 'GO', '1993-10-26', 'F');
INSERT INTO CDFUNCIONARIO (CDFCODIGO, CDFNOME, CDFENDERECO, CDFNUMERO, CDFCEP, CDFBAIRRO, CDFCIDADE, CDFUF, CDFDATANASCIMENTO, CDFSEXO)
                   VALUES (153, 'ALOIZIO LUZ DE ALMEIDA BARROS', 'SP 354', '5697', '46887439', 'CAROEBE', 'RECURSOLANDIA', 'PA', '1984-08-07', 'M');
                   
                   
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (0, 'ANTONIO %CARLOS FURMAN SAMPAIO', 'R JOSE DAVINHA', '1259', '18597-404', 'SAO FELIPE D''OESTE', 'DAVINOPOLIS', 'AP', '1965-03-02', 'M', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (1, 'ELICIO BARBOSA FERREIRA JR', 'R JOSE DAVINHA', '08', '17512572', 'VALE DO ANARI', 'URUCURITUBA', 'RJ', '1968-02-25', 'M', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (2, 'AGUINALDO RIBEIRO', 'AV DAS MACIEIRAS', '045', '17557-532', 'SAO FELIPE D''OESTE', 'CENTRO NOVO DO MARANHAO', 'BA', '1977-04-11', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (4, 'ERNESTO GALAFASSI GHINI', 'AV DA SAUDADE', '1236', '17557-532', 'PIMENTEIRAS DO OESTE', 'SAO JOAO DA BALIZA', 'TO', '1981-05-06', 'M', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (5, 'CLAUDEMIR BATISTA', 'R JOSE BONIFACIO', '1283', '13557-432', 'PACARAIMA', 'URUARA', 'DF', '1971-11-09', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (6, 'ADEMIR SCOBIN', 'AV PROF CARVALHO PINTO', '1320', '13557-432', 'CALDAZINHA', 'JAPONVAR', 'PI', '1984-11-22', 'F', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (7, 'CHIAPPINI', 'R SAO PAULO', NULL, '', 'PACARAIMA', 'DAVINOPOLIS', 'ES', '1981-10-01', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (8, 'ABEL MARIA DE CAMARGO', 'R JOÃO ARANHA', '1261', '', 'VALE DO ANARI', 'PORTEL', 'SP', '1961-09-12', 'M', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (10, 'ANTONIO MARCOS DA SILVA', 'R SAO PAULO', '1343', '17557-452', 'OURO PRETO DO OESTE', 'NOVA PORTEIRINHA', 'GO', '1984-05-09', 'F', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (11, 'CARLOS EDUARDO TEODORO DA ', 'R MICÃO', '1323', '18597-404', 'ROLIM DE MOURA', 'CHUPINGUAIA', 'CE', '1984-04-16', 'M', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (12, 'DILMAR JOSE', 'AV DOS TRABALHADORES', '1304', '18597-407', 'OURO PRETO DO OESTE', 'MONTE FORMOSO', 'MT', '1980-03-19', 'M', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (13, 'EDSON FRANCISCO DA FONSECA', 'R 10 DE ABRIL', '1250', '11111-111', 'SAO FELIPE D''OESTE', 'PORTEL', 'BA', '1973-03-13', 'M', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (14, 'ELICIO BARBOSA FERREIRA', 'R SAO BENEDITO', '1350', '', 'ROLIM DE MOURA', 'FLORESTA DO ARAGUAIA', 'MA', '1969-08-31', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (17, 'GALLANI', 'R 7 DE SETEMBRO', '1359', '11111-111', 'PRESIDENTE MEDICI', 'TABAPORA', 'GO', '1975-06-27', 'F', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (18, 'ALAN DIEGO NANINI', 'R SANTA GERTRUDES', '1307', '13557-432', 'TEIXEIROPOLIS', 'CAAPIRANGA', 'PI', '1985-04-16', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (20, 'ALESSANDRO MONTEIRO DE ', 'R JULIO DE TOLEDO', '06', '18597-404', 'PACARAIMA', 'COXIXOLA', 'MT', '1963-03-29', 'M', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (21, 'CICERO JOSE DA SILVA', 'R ROVIGO', '01325', '17557-452', 'PRESIDENTE MEDICI', 'TAMBORIL DO PIAUI', 'MA', '1967-09-07', 'M', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (22, 'CESAR DOS SANTOS DE AZEVEDO', 'AV PROF CARVALHO PINTO', '127', '17557-532', 'ROLIM DE MOURA', 'ARACOIABA', 'RS', '1972-07-27', 'M', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (23, 'EDINIR CARLOS MINOURO CUBO', 'R ANTONIO CARLOS NOGUEIRA', '1303', '', 'COSTA MARQUES', 'CAICARA DO NORTE', 'PA', '1980-06-23', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (25, 'ARI DE ALMEIDA', 'R JUVENAL L. DE CAMARGO', '1267', '', 'COSTA MARQUES', 'JENIPAPO DE MINAS', 'SP', '1966-12-14', 'M', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (26, 'CLAUDIA CRISTINA RODRIGUES ', 'R GUILHERME CONTESINE', '126', '', 'PRESIDENTE MEDICI', 'RECURSOLANDIA', 'ES', '1961-06-23', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (27, 'ANDRE LUIZ DA SILVA', 'R FRANCISCO ALVES SIQUEIRA', '1320', '17557-532', 'OURO PRETO DO OESTE', 'IPIXUNA DO PARA', 'ES', '1978-08-17', 'F', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (28, 'CLAUDEMIR LEMES BARBOSA', 'AV PAULICEIA', '134', '18597-407', 'PACARAIMA', 'FRANCISCOPOLIS', 'PA', '1977-01-06', 'M', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (29, 'CAMARGO', 'AV CENTENARIO DR PAULO DE ', '1327', '13557-432', 'ESPIGAO D''OESTE', 'SAO FRANCISCO DO PARA', 'PR', '1985-11-06', 'F', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (30, 'ANTONIO ALVES DE ALMEIDA FILHO', 'R MONTE CASTELO', '0694', '', 'PIMENTEIRAS DO OESTE', 'FLORESTA DO PIAUI', 'ES', '1982-09-01', 'M', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (31, 'ANTONIO ROBERTO PONTES', 'AV SAUDADE', '1237', '17557-452', 'SAO FELIPE D''OESTE', 'CAMPO AZUL', 'PR', '1979-12-20', 'M', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (32, 'ANDRE ANTONIO DE CASTILHO', 'R ANTONIO FESSEL', '134', '', 'PACARAIMA', 'SANTA FE DO ARAGUAIA', 'SE', '1962-03-31', 'M', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (34, 'MARIA DA SILVA', 'R FRANCISCO D. DE OLIVEIRA', NULL, '', 'JARU', 'MASSAPE DO PIAUI', 'RJ', '1974-11-17', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (35, 'CHARLES WEINGARTNER', 'R LARANJEIRAS', '1352', '', 'ESPIGAO D''OESTE', 'ALVORADA D''OESTE', 'BA', '1964-08-24', 'M', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (36, 'APARECIDO LIMA', 'R DR RUI BARBOSA', '1234', '18597-407', 'PIMENTEIRAS DO OESTE', 'PROFESSOR JAMIL', 'RR', '1979-08-07', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (37, 'ANDRE BERTELMANN MEYER', 'R HUMBERTO ROSSETI', '1323', '17557-452', 'PRESIDENTE MEDICI', 'RONDON DO PARA', 'AC', '1971-11-01', 'M', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (38, 'APARECIDA DE SOUZA LIMA ', 'R PROF JOAQUIM PEDROSO', '133', '13557-432', 'CANTA', 'SEBASTIAO LEAL', 'RS', '1962-08-01', 'F', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (39, 'CLAUDEMIR ALVES PEREIRA', 'R SEBASTIAO BUENO FERRAZ', '128', '', 'SAO FELIPE D''OESTE', 'CENTRAL DO MARANHAO', 'RO', '1984-01-13', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (40, 'SEBASTIÃO', 'R ATALIBA DE CARVALHO', '1260', '', 'ROLIM DE MOURA', 'ALMEIRIM', 'AM', '1982-04-18', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (41, 'ELEI SANTANA', 'R VEREADOR HERMINIO CONTESINI', '1342', '18597-407', 'TEIXEIROPOLIS', 'VITORIA DO JARI', 'RN', '1961-08-01', 'M', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (42, 'ALINE DE CASSIA KARWOWSKI', 'R LAVEIRO GIUZIO', '131-B', '', 'VALE DO ANARI', 'TUCUMA', 'MT', '1979-01-03', 'M', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (43, 'ALOIZIO LUZ DE ALMEIDA BARROS', 'AV WALDEMAR GOMES MARINHO', '1368', '13557-432', 'CEREJEIRA', 'SANTA LUZIA DO PARA', 'GO', '1962-04-04', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (44, 'ANDREA APARECIDA DE LIMA', 'R ANTONIO PEREIRA DA CRUZ', '1270', '13557-432', 'VALE DO ANARI', 'IMBE DE MINAS', 'GO', '1976-06-04', 'M', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (45, 'ADMILSON NUNES DE RESENDE', 'R PAULO ROBERTO BORELLI', NULL, '18597-404', 'PACARAIMA', 'PORTO DE MOZ', 'ES', '1981-10-22', 'F', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (46, 'CARLOS ALEXANDRE DA SILVA', 'R VALTER ZACARIAS', '127', '18597-404', 'CEREJEIRA', 'JUTAI', 'SP', '1984-06-07', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (47, 'ABEL MARIA DE CAMARGO', 'R PROF JOAQUIM PEDROSO', '0795', '', 'VALE DO ANARI', 'MASSAPE DO PIAUI', 'RS', '1980-07-08', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (49, 'ARI RODRIGUES DE OLIVEIRA', 'R AMAZONAS', '1280', '', 'PACARAIMA', 'SAO JOAO DO PACUI', 'MG', '1964-03-15', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (50, 'ARCANJO MONTEIRO TERRA', 'R JOSE ZACARIAS', '1283', '', 'CAROEBE', 'MARTINS SOARES', 'CE', '1979-10-29', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (51, 'BENY ALLAN ROLIM BARBOSA', 'R DR MOACIR DO AMARAL', '1333', '', 'OURO PRETO DO OESTE', 'JUVENILIA', 'PB', '1969-03-24', 'M', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (53, 'APARECIDA ELIZABETE RODRIGUES ', 'AV DONATELO', '1236', '18597-404', 'TEIXEIROPOLIS', 'PARAUAPEBAS', 'MA', '1982-06-03', 'F', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (54, 'CASSIO ROBERTO GUADRI', 'R JOAO XXIII', '07', '13557-432', 'CAROEBE', 'ASSIS BRASIL', 'RO', '1965-10-08', 'M', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (55, 'CARLOS MARCELINO DE JESUS', 'R PEDRO RENATO LORENCINI', '133', '18597-404', 'VALE DO ANARI', 'DARCINOPOLIS', 'TO', '1982-12-21', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (56, 'ELISEU BRANCO', 'R JOAO PESSOA', '128', '', 'PIMENTEIRAS DO OESTE', 'COTRIGUACU', 'DF', '1969-12-19', 'M', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (57, 'CHARKES ALBERT FERNANDES ', 'R JOSE EDUARDO', '1264', '17557-452', 'SAO FELIPE D''OESTE', 'BACABEIRA', 'SE', '1974-09-10', 'F', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (58, 'EDVALDO LUIS GOMES', 'R CANARIO', '127', '17557-532', 'ROLIM DE MOURA', 'TRAIRAO', 'MG', '1971-09-17', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (59, 'ERIC EMILIO DE CAMPOS', 'R BORTO CARAO', '1287', '', 'CANTA', 'CACHOEIRA GRANDE', 'MT', '1983-04-03', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (61, 'EDILSON JOSÉ DA SILVA', 'ALAMEDA AGOSTINHO DELLA ', '1237', '', 'JARU', 'PEDRO DO ROSARIO', 'TO', '1974-03-26', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (62, 'ANTONIO JOAO DA SILVA', 'AV LUIS MILANO FILHO', '125', '11111-111', 'VALE DO ANARI', 'NOVO PROGRESSO', 'RO', '1980-07-09', 'F', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (63, 'APARECIDO LIMA', 'R ALADINO SELMI', '1270', '', 'PRESIDENTE MEDICI', 'MINISTRO ANDREAZZA', 'SP', '1979-02-03', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (64, 'DOUGLAS MARCELO VIEIRA', 'SP 354', '1254', '', 'PIMENTEIRAS DO OESTE', 'NOVA BELEM', 'ES', '1962-08-15', 'M', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (65, 'DIRCE APARECIDA CUNHA MACIEL', 'R RICARDO ZERBI NATI', '1352', '', 'PACARAIMA', 'BOQUEIRAO DO PIAUI', 'PR', '1972-06-24', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (67, 'ALEIXO MAX MAZZAQUATRO', 'R DAVID LOPES DE CAMARGO', '1263', '', 'CEREJEIRA', 'LIMOEIRO DO AJURU', 'AL', '1975-05-24', 'F', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (68, 'ANTANIO LUIZ VIEIRA DO ', 'R LUIZ STRAZZACAPA', '01376', '18597-404', 'TEIXEIROPOLIS', 'JUNCO DO MARANHAO', 'DF', '1977-03-28', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (69, 'ADSON DO NASCIMENTO BARBOSA', 'R ALVARENGA PEIXOTO', '1259', '17557-452', 'CAROEBE', 'SETUBINHA', 'PR', '1965-02-22', 'F', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (70, 'ANGELO ANDRE BRUSTOLIN ', 'R ANCHIETA', '135', '11111-111', 'COLORADO DO OESTE', 'SANTO ANTONIO DO ICA', 'SP', '1969-12-02', 'M', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (71, 'DANIELLE BITTENCOURT LIASCH', 'AV DONATELO', '1359', '13557-432', 'VALE DO ANARI', 'SANTO AMARO DO MARANHAO', 'PB', '1979-03-01', 'M', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (72, 'ANDERSON OLIVEIRA DA SILVA', 'R RAUL SILVA', '1270', '', 'JARU', 'BACURI', 'MG', '1981-09-03', 'M', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (73, 'ADEMAR PORTO', 'R LUIZ STRAZZACAPA', '02', '17557-532', 'ROLIM DE MOURA', 'ALTO CAPARAO', 'MG', '1981-01-22', 'F', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (74, 'OLIVEIRA', 'R LUIZ STRAZACAPA', '1271', '18597-404', 'CEREJEIRA', 'ASSUNCAO DO PIAUI', 'AP', '1963-10-20', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (75, 'EMERSON CASSIA DA SILVA', 'R ANTONIO FERRAZO', '1280', '13557-432', 'AMAJARI', 'UIRAPURU', 'AC', '1963-07-06', 'M', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (76, 'TEIXEIRA', 'R DAURI GOES DE MORAES', '028', '', 'CANTA', 'LAGOA DA CONFUSAO', 'MG', '1985-12-24', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (77, 'ADAIR JOSE MANUEL', 'R PEDRO RENATO LORENCINI', '1280', '', 'ROLIM DE MOURA', 'UNIAO DE MINAS', 'PB', '1968-11-07', 'M', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (78, 'ADELCIO RODRIGUES DE AGUILAR', 'R EUGENIO BERTTI', '066', '', 'PIMENTEIRAS DO OESTE', 'CURRALINHO', 'PA', '1978-06-13', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (79, 'ARIOVALDO JOSE PINTO', 'R DR ADEMAR PEREIRA DE BARROS', '126', '', 'JARU', 'PAULINO NEVES', 'AC', '1964-06-26', 'F', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (80, 'ANDERSON ROBERTO DE OLIVEIRA', 'R DINO BANCHIERI', '018', '', 'PRESIDENTE MEDICI', 'SAO GERALDO DO BAIXIO', 'RO', '1984-04-11', 'M', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (81, 'ALEXANDRE DE ARAUJO AMORIM', 'R ALBERTO STUCKI', '1281', '17557-532', 'ESPIGAO D''OESTE', 'ALMEIRIM', 'PB', '1966-06-07', 'M', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (82, 'ADEMIR ANTONIO', 'R ANDRE MADSEN', '1362', '', 'COLORADO DO OESTE', 'SAO RAIMUNDO DO DOCA BEZERRA', 'AP', '1968-03-16', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (84, 'ANTONIA ANGELICA FOGASA', 'R GUADALAJARA', '1237', '', 'ROLIM DE MOURA', 'TOCOS DO MOJI', 'BA', '1984-10-12', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (85, 'ELIDIONE FELIPE MEDEIROS', 'R ANTONIO SOUZA PEREZ', '1261', '18597-404', 'IRACEMA', 'SAO LUIZ', 'RN', '1978-04-10', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (86, 'ALLAN MAGIOLI', 'R TIRADENTES', '1368', '18597-407', 'VALE DO ANARI', 'ARAGOMINAS', 'TO', '1964-10-09', 'M', 'T');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (87, 'ALOIZIO LUZ DE ALMEIDA BARROS', 'R 7 DE ABRIL', '1276', '17557-532', 'CANTA', 'PAU D''ARCO', 'PA', '1985-10-25', 'F', 'F');
INSERT INTO CDCLIENTE (CDCLICODIGO, CDCLINOME, CDCLIENDERECO, CDCLINUMERO, CDCLICEP, CDCLIBAIRRO, CDCLICIDADE, CDCLIUF, CDCLIDATANASCIMENTO, CDCLISEXO, CDCLIATIVO)
               VALUES (88, 'JERONIMOS SILVA', 'R 10 DE ABRIL', '85', '17512-856', 'SERRARIA', 'GUAJARA', 'RO', NULL, NULL, NULL);


INSERT INTO CDESCOLA (CDECODIGO, CDEDESCRICAO)
              VALUES (1, 'EMEI JOSE ALMEIDA PPPP');
INSERT INTO CDESCOLA (CDECODIGO, CDEDESCRICAO)
              VALUES (2, 'EMEF CASTRO ALVES');
INSERT INTO CDESCOLA (CDECODIGO, CDEDESCRICAO)
              VALUES (3, 'EMEI MONTEIRO LOBATO');
INSERT INTO CDESCOLA (CDECODIGO, CDEDESCRICAO)
              VALUES (4, 'EMEF CRISTOVAO COLOMBO');
              
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (1, 79, 23, '2011-07-13 00:00:00', 96.5);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (2, 12, 46, '2011-09-11 00:00:00', 40.36);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (4, 68, 44, '2011-01-01 00:00:00', 95.61);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (5, 61, 30, '2011-07-03 00:00:00', 71.66);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (6, 55, 46, '2011-03-22 00:00:00', 42.15);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (7, 64, 43, '2012-01-16 00:00:00', 75.6);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (8, 23, 29, '2011-09-08 00:00:00', 16.1);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (10, 81, 35, '2011-02-12 00:00:00', 71.95);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (11, 20, 18, '2011-03-30 00:00:00', 9.6);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (12, 13, 22, '2011-01-07 00:00:00', 49.41);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (13, 69, 6, '2011-11-20 00:00:00', 5.69);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (14, 57, 36, '2011-10-31 00:00:00', 11.86);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (17, 54, 11, '2011-11-11 00:00:00', 55.77);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (18, 42, 14, '2011-09-14 00:00:00', 53.28);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (20, 49, 37, '2011-05-03 00:00:00', 83.98);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (21, 38, 42, '2011-06-02 00:00:00', 81.94);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (23, 55, 29, '2011-08-11 00:00:00', 46.76);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (24, 55, 8, '2011-01-12 00:00:00', 1.93);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (25, 27, 43, '2011-05-19 00:00:00', 29.15);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (26, 58, 34, '2011-01-29 00:00:00', 37.02);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (27, 50, 36, '2011-09-22 00:00:00', 13.19);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (28, 79, 22, '2011-07-18 00:00:00', 4.75);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (29, 68, 7, '2011-01-07 00:00:00', 53.75);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (30, 65, 12, '2011-12-11 00:00:00', 19);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (31, 37, 42, '2011-08-30 00:00:00', 40.03);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (32, 47, 28, '2011-01-05 00:00:00', 25.08);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (33, 50, 38, '2011-03-06 00:00:00', 99.44);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (34, 14, 17, '2011-09-11 08:00:00', 10.35);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (35, 57, 17, '2011-07-30 00:00:00', 92.51);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (36, 80, 11, '2011-07-05 00:00:00', 85.48);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (37, 54, 35, '2011-12-15 00:00:00', 34.49);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (38, 85, 6, '2011-06-26 00:00:00', 21.5);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (39, 24, 39, '2011-05-10 00:00:00', 48.13);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (40, 42, 25, '2011-05-13 00:00:00', 44.63);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (41, 21, 41, '2011-11-26 00:00:00', 49.57);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (43, 56, 45, '2011-03-23 00:00:00', 58.39);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (44, 28, 31, '2011-10-03 00:00:00', 26.28);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (45, 8, 42, '2011-09-19 00:00:00', 41.82);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (46, 76, 13, '2012-01-08 00:00:00', 41.09);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (47, 31, 25, '2011-08-13 00:00:00', 22.08);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (49, 7, 25, '2011-06-17 00:00:00', 28.28);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (50, 73, 28, '2011-01-08 00:00:00', 69.68);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (51, 37, 21, '2011-11-09 00:00:00', 20.19);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (52, 30, 32, '2011-06-23 00:00:00', 23.98);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (53, 40, 5, '2011-05-19 00:00:00', 5.38);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (54, 52, 21, '2011-12-27 00:00:00', 15.75);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (57, 78, 7, '2011-04-21 00:00:00', 58.1);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (59, 57, 37, '2012-01-05 00:00:00', 90.33);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (60, 46, 26, '2011-09-29 00:00:00', 16.96);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (61, 4, 21, '2011-08-16 00:00:00', 47.84);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (62, 46, 43, '2011-06-28 00:00:00', 64.97);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (63, 48, 8, '2011-03-30 00:00:00', 4.06);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (64, 83, 5, '2011-01-30 00:00:00', 23.65);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (65, 70, 30, '2011-06-02 00:00:00', 67.07);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (66, 16, 46, '2011-05-18 00:00:00', 41.13);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (67, 46, 25, '2011-09-16 00:00:00', 61.02);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (68, 75, 21, '2012-01-12 00:00:00', 25.75);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (69, 2, 7, '2011-07-20 00:00:00', 59.83);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (70, 73, 7, '2011-10-13 00:00:00', 58.61);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (71, 61, 45, '2011-04-05 00:00:00', 1.02);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (72, 72, 11, '2011-08-09 00:00:00', 85.41);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (73, 20, 21, '2011-04-29 00:00:00', 64.02);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (74, 29, 28, '2012-01-07 00:00:00', 40.31);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (75, 3, 12, '2011-03-29 00:00:00', 5.83);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (77, 41, 23, '2011-05-05 00:00:00', 69.18);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (78, 67, 11, '2011-11-27 00:00:00', 35.24);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (80, 47, 41, '2012-01-18 00:00:00', 56.9);
INSERT INTO LCATENDIMENTO (LCACODIGO, LCAFUNCIONARIO, LCACLIENTE, LCADATAHORA, LCAVALOR)
                   VALUES (1000, 150, 23, '2021-09-22 00:00:00', 23.01);


  
                   
                   




                   
                   